= Community Graph

This is the start of a project that will allow you to create a community graph that collects data from Twitter, GitHub, StackOverflow, and Meetup and stores it in a Neo4j graph.
You'll then have a database that you can query as well as a dashboard which summarises the community activity over the last week

If you have any questions please send us an email devrel@neo4j.com

== Pre requisites

You'll need to have the following installed:

```
Node.js 6.7.0
Python  3.6.0
```

== How do I use it?

At the moment you'll need to hardcode the following values into a `communitygraph.json` file:

```
{
  "communityName": "Community Name Here",
  "tag": "Tag for searching on GitHub",
  "s3Bucket": "Name of S3 bucket",
  "logo": "Path to an image of your community",
  "serverUrl": "IP Address/Hostname of Neo4j Instance",
  "twitterSearch": "Twitter search term",
  "credentials": {
    "keyArn": "KMS Key ARN",
    "meetupApiKey": "Meetup API key (encrypted by KMS key)",
    "githubToken": "GitHub Token (encrypted by KMS key)",
    "twitterBearer": "Twitter Bearer (encrypted by KMS key)",
    "readonly": {
      "user": "Neo4j user name",
      "password": "Neo4j password (encrypted by KMS key)"
    },
    "write": {
      "user": "Neo4j user name",
      "password": "Neo4j password (encrypted by KMS key)"
    }
  }
}
```

You'll also need to make sure you have your AWS credentials in `~/.aws/credentials`.

You can run:

```
npm install -g .
community-graph
```

We'll be automating more of this so it's a more friendly user experience so check back soon and hopefully it'll be simpler.

== Things to do

* [*] Add lambdas to import data from StackOverflow
* [*] Add lambdas to import data from Meetup
* [*] Add lambdas to import data from Twitter
* [*] Add lambdas to import data from GitHub
* [ ] Interactive `community-graph` so that users can set parameters
* [ ] Generate `communitygraph.json` file based on parameters passed into the `community-graph` command
* [ ] Create S3 bucket to put summary page
* [ ] Permissions for S3 bucket <-> lambda user
* [ ] Generate KMS key
* [ ] Encrypt passwords using KMS key
* [ ] Spin up Neo4j server using AWS AMI
* [ ] Delete `__pycache__` directory at the end of a failing run
* [ ] Install APOC on the Neo4j server
* [ ] Run all the lambdas once on creation
* [ ] Run the twitter lambda with `catch-up: false`

