service: community-graph

frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  stage: "${opt:stage, self:provider.stage}"
  kmsKeyArn: ${file(communitygraph.json):credentials.keyArn}

provider:
  name: aws
  runtime: python3.6
  timeout: 180
  iamRoleStatements:
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource:
        - ${self:custom.kmsKeyArn}

package:
  exclude:
    - node_modules/**
    - a/**

plugins:
  - serverless-python-requirements

functions:
  page-summary:
      name: CommunityGraphCLI-GeneratePageSummary
      handler: handler.generate_page_summary
      events:
        - schedule: rate(1 hour)
  so-import:
      name: CommunityGraphCLI-StackOverflowImport
      handler: handler.so_import
      events:
        - schedule: rate(1 hour)
  meetup-events-import:
      name: CommunityGraphCLI-MeetupEventsImport
      handler: handler.meetup_events_import
      events:
        - schedule: rate(1 hour)
  meetup-groups-import:
      name: CommunityGraphCLI-MeetupGroupsImport
      handler: handler.meetup_groups_import
      events:
        - schedule: rate(1 day)
  github-import:
      name: CommunityGraphCLI-GitHubImport
      handler: handler.github_import
      events:
        - schedule: rate(1 hour)
  twitter-import:
      name: CommunityGraphCLI-TwitterImport
      handler: handler.twitter_import
      events:
        - schedule: rate(1 hour)
  twitter-clean-links:
      name: CommunityGraphCLI-TwitterCleanLinks
      handler: handler.twitter_clean_links
      events:
        - schedule: rate(1 hour)
  twitter-hydrate-links:
      name: CommunityGraphCLI-TwitterHydrateLinks
      handler: handler.twitter_hydrate_links
      events:
        - schedule: rate(1 hour)
  twitter-unshorten-links:
      name: CommunityGraphCLI-TwitterUnshortenLinks
      handler: handler.twitter_unshorten_links
      events:
        - schedule: rate(1 hour)