service: community-graph

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  timeout: 180

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-python-requirements

functions:
  page-summary:
      name: CommunityGraphCLI-GeneratePageSummary
      handler: handler.generate_page_summary
      events:
        - schedule: rate(1 hour)
