service: community-graph

useDotenv: true
custom:
  stage: "${opt:stage, self:provider.stage}"
  communityName: ${env:COMMUNITY_NAME}
  s3Bucket: ${env:S3_BUCKET}

provider:
  name: aws
  stage: ${opt:stage, self:provider.stage}
  runtime: python3.7
  timeout: 180

  Resources:
    S3BucketPermissions:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.s3Bucket}
        PolicyDocument:
          Statement:
            - Principal: "*"
              Action:
                - s3:GetObject
              Effect: Allow
              Sid: "AddPerm"
              Resource: arn:aws:s3:::${self:custom.s3Bucket}/*



package:
  patterns:
    - "!node_modules/**"
    - "!a/**"
    - "!venv/**"
    - "!venv2/**"

plugins:
  - serverless-python-requirements
  - serverless-offline

functions:
  # page-summary:
  #     name: CommunityGraphCLI-${self:custom.communityName}-GeneratePageSummary
  #     handler: handler.generate_page_summary
  #     events:
  #       - schedule: rate(1 hour)
  page-http-summary:
    name: CommunityGraphCLI-${self:custom.communityName}-HttpPageSummary
    handler: handler.summary_page
    events:
      - http:
          path: /
          method: get
  so-import:
      name: CommunityGraphCLI-${self:custom.communityName}-StackOverflowImport
      handler: lib.so.handler
      events:
        - schedule: rate(1 hour)
  meetup-events-import:
      name: CommunityGraphCLI-${self:custom.communityName}-MeetupImport
      handler: lib.meetup.handler
      events:
        - schedule: rate(1 hour)
  # meetup-events-import:
  #     name: CommunityGraphCLI-${self:custom.communityName}-MeetupEventsImport
  #     handler: handler.meetup_events_import
  #     events:
  #       - schedule: rate(1 hour)
  # meetup-groups-import:
  #     name: CommunityGraphCLI-${self:custom.communityName}-MeetupGroupsImport
  #     handler: handler.meetup_groups_import
  #     events:
  #       - schedule: rate(1 day)
  github-import:
      name: CommunityGraphCLI-${self:custom.communityName}-GitHubImport
      handler: lib.github.handler
      events:
        - schedule: rate(1 hour)
  twitter-import:
      name: CommunityGraphCLI-${self:custom.communityName}-TwitterImport
      handler: lib.twitter.handler
      events:
        - schedule: rate(1 minute)

  constraints:
      name: CommunityGraphCLI-${self:custom.communityName}-Constraints
      handler: handler.constraints